### ISSUE TITLE
How to generate a set of UML diagrams of an existing project in Enterprise-Architect?

### ISSUE THREAD

**Issue by jhon65496** [aljoshakoecher/BPMN-Code-Generator#1]
How to generate a set of UML diagrams of an existing project in Enterprise-Architect?

For example, I took a project.
https://github.com/NBull92/Northwind-MVVM-Survival-Guide/

I get the result as in the picture.
This is Class Diagrams.
How to generate diagrams:
- Activity Diagrams
- Component Diagrams
- Sequence Diagrams
- Use Case Diagrams

How do I generate all or part of the charts? 
I didn't find the Enterprise-Architect documentation where it was well described.
I couldn't quite figure it out.
=== === === === === === === ===

Note.
Sorry for writing to you by Email.
I found your Email by the principle: github.com > mdd4all.de

I am studying C# programming.
I'm trying to deal with Enterprise-Architect.

**Pic1**
![image](https://github.com/aljoshakoecher/BPMN-Code-Generator/assets/128128859/d3cf6b66-3e4f-4bfd-a165-8356cd4b83cb)

**Comment by aljoshakoecher** [comment]
I am super confused by your question as it has nothing to do with this repository... You might better ask this question in the Enterprise Architect forums.

You cannot automatically generate diagrams from thin air, how is that supposed to work? In order to create a new diagram, you can simply click the "New Diagram" button at the top of the project browser (left in your screenshot). Then select your diagram type and start modeling.

But I cannot give any more help here as it's completely unrelated to this repo and I am thus closing this issue. As I said, you might better ask this question in the Enterprise Architect forums.
